quarkus.application.name=core-banking

########################################
# DATABASE (PostgreSQL)
########################################

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/corebank

# Connection pool (good default)
quarkus.datasource.jdbc.max-size=16

########################################
# HIBERNATE ORM
########################################

# IMPORTANT: Flyway will control schema
quarkus.hibernate-orm.database.generation=none

# Optional (debug)
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.format-sql=true

########################################
# FLYWAY
########################################

# Run migrations automatically at startup
quarkus.flyway.migrate-at-start=true

# (default location already correct, but explicit is good)
quarkus.flyway.locations=db/migration

########################################
# SCHEDULER (for SQS polling)
########################################

quarkus.scheduler.enabled=true

########################################
# AWS SQS (LocalStack)
########################################

app.sqs.queue-url=http://localhost:4566/000000000000/conta-bancaria-criada
aws.region=sa-east-1
aws.access-key=test
aws.secret-key=test
aws.endpoint=http://localhost:4566

########################################
# LOGGING
########################################

quarkus.log.level=INFO
quarkus.log.category."br.com.vgn".level=DEBUG
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) [correlationId=%X{correlationId}] %s%e%n

########################################
# HTTP
########################################

quarkus.http.port=8081
quarkus.http.root-path=/api/v1


########################################
# OBSERVABILITY
########################################

quarkus.otel.enabled=true
quarkus.otel.service.name=core-banking
quarkus.otel.traces.exporter=otlp
quarkus.otel.exporter.otlp.endpoint=http://localhost:4318
quarkus.otel.exporter.otlp.protocol=http/protobuf
quarkus.otel.traces.sampler=always_on
quarkus.otel.simple=true