package br.com.vgn.common.exception

enum class ErrorCode(val code: String) {
    INVALID_AMOUNT("INVALID_AMOUNT"),
    INVALID_CURRENCY("INVALID_CURRENCY"),
    ACCOUNT_NOT_FOUND("ACCOUNT_NOT_FOUND"),
    IDEMPOTENCY_CONFLICT("IDEMPOTENCY_CONFLICT"),
    BAD_REQUEST("BAD_REQUEST"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR")
}